CREATE TABLE "error_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "error_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer,
	"level" varchar(20) DEFAULT 'ERROR' NOT NULL,
	"context" varchar(255),
	"message" text NOT NULL,
	"stack" text,
	"metadata" json,
	"endpoint" varchar(255),
	"method" varchar(10),
	"requestId" varchar(255),
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tasks" ADD COLUMN "jobId" varchar NOT NULL;--> statement-breakpoint
ALTER TABLE "error_logs" ADD CONSTRAINT "error_logs_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;